name: databricks-support-app
command:
  - "sh"
  - "-c"
  - "chmod +x ./support-app && ./support-app"

env:
  - name: DB_HOST
    valueFrom: secret:lakebase_scope:db_host
  - name: DB_PORT
    valueFrom: secret:lakebase_scope:db_port
  - name: DB_USER
    valueFrom: secret:lakebase_scope:db_user
  - name: DB_PASSWORD
    valueFrom: secret:lakebase_scope:db_password
  - name: DB_NAME
    valueFrom: secret:lakebase_scope:db_name
  - name: DB_SSLMODE
    value: "require"